"""add end_at to interview_sessions

Revision ID: 09c6443dae36
Revises: cb5edb9d894c
Create Date: 2025-07-16 19:48:41.947916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09c6443dae36'
down_revision: Union[str, Sequence[str], None] = 'cb5edb9d894c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('end_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.drop_column('interview_sessions', 'duration_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('interview_sessions', 'end_at')
    # ### end Alembic commands ###
