"""cascade user_answers when deleting questions

Revision ID: 394706ad0e98
Revises: ff9a48a38773
Create Date: 2025-07-28 23:47:21.958732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '394706ad0e98'
down_revision: Union[str, Sequence[str], None] = 'ff9a48a38773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
