"""Use AI-generated questions for session questions

Revision ID: cb5edb9d894c
Revises: 364590b633f3
Create Date: 2025-07-16 10:57:07.082745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb5edb9d894c'
down_revision: Union[str, Sequence[str], None] = '364590b633f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_questions', sa.Column('question_title', sa.String(length=255), nullable=False))
    op.add_column('session_questions', sa.Column('question_description', sa.Text(), nullable=True))
    op.add_column('session_questions', sa.Column('question_type', sa.String(length=20), nullable=True))
    op.add_column('session_questions', sa.Column('difficulty', sa.String(length=10), nullable=True))
    op.drop_constraint(op.f('session_questions_question_id_fkey'), 'session_questions', type_='foreignkey')
    op.drop_column('session_questions', 'question_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_questions', sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('session_questions_question_id_fkey'), 'session_questions', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_column('session_questions', 'difficulty')
    op.drop_column('session_questions', 'question_type')
    op.drop_column('session_questions', 'question_description')
    op.drop_column('session_questions', 'question_title')
    # ### end Alembic commands ###
