"""add function name and params to question model

Revision ID: ff9a48a38773
Revises: 96d7e3e65ebd
Create Date: 2025-07-27 09:25:04.560889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff9a48a38773'
down_revision: Union[str, Sequence[str], None] = '96d7e3e65ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('function_name', sa.String(length=100), nullable=True))
    op.add_column('questions', sa.Column('parameters', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'parameters')
    op.drop_column('questions', 'function_name')
    # ### end Alembic commands ###
